# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoloosiPro' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
   pod 'Foloosi-iOS-SDK', '~> 1.3.9'

  # Pods for FoloosiPro

end
